# Generated by Django 3.2.9 on 2021-11-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211122_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='ram_category',
            field=models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB')], max_length=100),
        ),
    ]
