# Generated by Django 3.2.9 on 2021-11-23 05:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211122_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='ram_category',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='storage_category',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color')], default=2000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
