# Generated by Django 3.2.9 on 2021-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
