# Generated by Django 3.2.9 on 2021-11-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
    ]
