# Generated by Django 3.2.9 on 2021-11-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_banners_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
