# Generated by Django 3.2.9 on 2021-12-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_banners_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='category',
        ),
    ]
