# Generated by Django 3.2.9 on 2021-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_banners_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
