# Generated by Django 3.2.9 on 2021-11-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211126_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pin',
            new_name='pincode',
        ),
    ]
